global:
  scrape_interval: 10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-prom'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'hashmap-ms'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:4500']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
